- hosts: localhost
  become: false
  roles:
    - apps
    - snap
    - vim
    - tmux
    - emacs
    - tig
    - bash
    - i3
    - hibernate
  tasks:
    - name: block ssh by firewall
      become: true
      firewalld:
        service: ssh
        permanent: yes
        state: disabled

