- hosts: localhost
  become: false
  pre_tasks:
    - name: store dotfiles dir path in a var
      set_fact:
        dotfiles_dir: "{{ lookup('env', 'HOME') }}/Dropbox/df"
  roles:
    - packages
    - vim
    - tmux
    - emacs
    - tig
    - bash
    # - i3
    - hibernate
    - firewall
    - nodejs

