- hosts: localhost
  become: false
  pre_tasks:
    - name: store dotfiles dir path in a var
      set_fact:
        dotfiles_dir: "{{ lookup('env', 'HOME') }}/Dropbox/df"
  roles:
    - role: packages
      tags:
        - packages
    - role: vim
      tags:
        - vim
    - role: tmux
      tags:
        - tmux
    - role: emacs
      tags:
        - emacs
    - role: tig
      tags:
        - tig
    - role: bash
      tags:
        - bash
    - role: i3
      tags:
        - i3
    - role: hibernate
      tags:
        - hibernate
    - role: firewall
      tags:
        - firewall
    - role: nodejs
      tags:
        - nodejs
    - role: gpg
      tags:
        - gpg
    - role: tailscale
      tags:
        - tailscale
