- hosts: localhost
  become: false
  roles:
    - vim
    - tmux
    - emacs
    - tig
    - bash
  tasks:
    - name: install essential packages
      become: true
      dnf:
        name:
          - zeal
          - git
          - firefox
          - "{{ dropbox_rpm_url }}"
          - the_silver_searcher
          - keepassxc
          - chromium
          - gnucash
          - fzf
          - jq
          - ncdu
        state: present
    - name: block ssh by firewall
      become: true
      firewalld:
        service: ssh
        permanent: yes
        state: disabled

