- hosts: localhost
  become: false
  vars:
    dotfiles_dir: "{{ lookup('env', 'HOME') }}/sync/df"
    private_dotfiles_dir: "{{ lookup('env', 'HOME') }}/private/df"
  tasks:
    - name: link private configs
      file:
        src: "{{ private_dotfiles_dir }}/{{ item.src }}"
        path: "{{ item.dest }}"
        state: link
      loop:
        - {src: "ssh/config", dest: "~/.ssh/config"}
  roles:
    - { role: packages, tags: packages }
    - { role: alacritty, tags: alacritty }
    - { role: vim, tags: vim }
    - { role: nvim, tags: nvim }
    - { role: tmux, tags: tmux }
    - { role: tig, tags: tig }
    - { role: bash, tags: bash }
    - { role: i3, tags: i3 }
    - { role: hibernate, tags: hibernate }
    - { role: firewall, tags: firewall }
    - { role: nodejs, tags: nodejs }
    - { role: gpg, tags: gpg }
    - { role: tailscale, tags: tailscale }
    - { role: syncthing, tags: syncthing }
