- hosts: localhost
  become: false
  pre_tasks:
    - set_fact:
        dotfiles_dir: "{{ lookup('env', 'PWD') }}/dotfiles"
  roles:
    - packages
    - vim
    - tmux
    - emacs
    - tig
    - bash
    - i3
    - hibernate
    - firewall

