- name: Install packages for Fedora
  include_tasks: fedora/main.yml
  when: ansible_distribution == 'Fedora'

- name: Install packages for macOS
  include_tasks: macos/main.yml
  when: ansible_distribution == 'MacOSX'
