- name: create apps dir
  file:
    name: "{{ fedora.appimage.install_dir }}"
    state: directory

- name: create bin dir for symlinks
  file:
    name: "{{ fedora.appimage.bin_dir }}"
    state: directory

- name: install packages
  include_tasks: package.yml
  loop: "{{ fedora.appimage.packages }}"
  loop_control:
    loop_var: appimage_package

