# TODO: check it it's already downloaded
- name: download the package for {{ appimage_package }}
  get_url:
    url: "{{ appimage_package.url }}"
    dest: "{{ fedora.appimage.install_dir }}"
    checksum: "{{ appimage_package.checksum }}"
    mode: 0700
  register: downloaded_package

- name: make a symlink
  file:
    path: "{{ fedora.appimage.bin_dir }}/{{ appimage_package.name }}"
    src: "{{ downloaded_package.dest }}"
    state: link
