- name: install tig
  become: true
  dnf:
    name: tig
    state: present

- name: link the config
  file:
    src: "{{ dotfiles_dir }}/{{ item }}"
    path: "~/{{ item }}"
    state: link
  loop:
    - .tigrc
