- name: install tig
  become: true
  dnf:
    name: tig
    state: present

- name: link the config
  file:
    src: "~/Dropbox/df/{{ item }}"
    path: "~/{{ item }}"
    state: link
  loop:
    - .tigrc
