- name: install nvim
  become: true
  apt:
    name:
      - nvim
    install_recommends: no
    state: present

- name: install packages required by YCM
  become: true
  apt:
    name:
      - build-essential
      - cmake
      - vim-nox
      - python3-dev
      - golang
      - nodejs
      - npm
    state: present

- name: install additional packages
  become: true
  apt:
    name:
      - fzf
      - ripgrep
    install_recommends: no
    state: present
