- name: install prerequisites for PPA
  become: true
  apt:
    name:
      - software-properties-common
    install_recommends: no
    state: present

- name: add PPA repo
  become: true
  apt_repository:
    repo: 'ppa:neovim-ppa/stable'

- name: install packages for YCM
  become: true
  apt:
    name:
      - python3-dev
      - python3-pip
      - build-essential
      - cmake
      - golang
      - nodejs
      - npm
    state: present

- name: install neovim
  become: true
  apt:
    name:
      - neovim
    install_recommends: no
    state: present

- name: install additional packages
  become: true
  apt:
    name:
      - fzf
      - ripgrep
    install_recommends: no
    state: present

- name: install bob nvim manager
  ansible.builtin.unarchive:
    src: "{{ nvim_bob_url }}"
    dest: ~/bin
    remote_src: yes
    mode: 'u=rwx'
