- name: install required packages
  become: true
  dnf:
    name:
      - i3
      - i3status
      - network-manager-applet
      - feh
      - pavucontrol
      - kmix
      - arandr
      - kmix
      - dunst
    state: present
- name: copy the i3 configs
  copy:
    src: i3
    dest: ~/.config
- name: create the bin directory
  file:
    path: ~/.config/i3/bin
    state: directory
- name: copy related scripts
  copy:
    src: "{{ item }}"
    dest: ~/.config/i3/bin
    mode: 0744
  with_items:
    - bin/kde-services
    - bin/i3-toggle-bar
- name: configure dunst
  copy:
    src: dunst
    dest: ~/.config
