- name: install required packages
  become: true
  dnf:
    name:
      - i3
      - i3status
      - network-manager-applet
      - feh
      - pavucontrol
      - kmix
      - arandr
      - kmix
      - dunst
    state: present

- name: copy the i3 configs
  copy:
    src: i3
    dest: ~/.config

- name: create the bin directory
  file:
    path: ~/.config/i3/bin
    state: directory

- name: copy related scripts
  copy:
    src: "{{ item }}"
    dest: ~/.config/i3/bin
    mode: 0744
  with_items:
    - bin/kde-services
    - bin/i3-toggle-bar

- name: configure dunst
  copy:
    src: dunst
    dest: ~/.config

- name: copy config for systemd service that locks the screen
  become: true
  copy:
    src: suspend@.service
    dest: /etc/systemd/system

- name: enable the service
  become: true
  systemd:
    name: suspend@pi
    enabled: yes
    daemon_reload: yes
