- name: install emacs
  become: true
  dnf:
    name: emacs
    state: present

- name: link the config
  file:
    src: "{{ dotfiles_dir }}/{{ item }}"
    path: "~/{{ item }}"
    state: link
  loop:
    - .spacemacs

- name: clone spacemacs and switch to develop version
  git:
    repo: "https://github.com/syl20bnr/spacemacs.git"
    dest: "~/.emacs.d"
    version: develop
    update: no
