- name: install emacs
  become: true
  dnf:
    name: emacs
    state: present

- name: copy the config
  copy:
    src: ".spacemacs"
    dest: "~/"

- name: clone spacemacs and switch to develop version
  git:
    repo: "https://github.com/syl20bnr/spacemacs.git"
    dest: "~/.emacs.d"
    version: develop
    update: no
