- name: install vim with support for X11
  become: true
  dnf:
    name: vim-X11
    state: present

- name: install packages required by YCM
  become: true
  dnf:
    name:
      - cmake
      - gcc-c++
      - make
      - python3-devel
      - golang
      - nodejs
      - npm
    state: present
