- name: install vim
  become: true
  dnf:
    name:
      - vim-X11
      - vim-enhanced
    state: present

- name: install packages required by YCM
  become: true
  dnf:
    name:
      - cmake
      - gcc-c++
      - make
      - python3-devel
      - golang
      - nodejs
      - npm
    state: present
