- name: install tmux
  become: true
  dnf:
    name: tmux
    state: present

- name: link the configs
  file:
    src: "~/Dropbox/df/{{ item }}"
    path: "~/{{ item }}"
    state: link
  loop:
    - .tmux.conf
    - .tmux
