- name: install required packages
  include_tasks: packages/main.yml

- name: link the configs
  file:
    src: "{{ dotfiles_dir }}/{{ item }}"
    path: "~/{{ item }}"
    state: link
  loop:
    - .tmux.conf
    - .tmux
