- name: save fedora release version into a variable
  command: "rpm -E %fedora"
  register: fedora_release

- name: enable rpm fusion repo
  become: true
  dnf:
    name: "{{ item | replace('$fedora_release', fedora_release.stdout) }}"
    state: present
  loop:
    - "{{ fedora.rpm_fusion_url.free }}"
    - "{{ fedora.rpm_fusion_url.nonfree }}"

- name: install essential packages
  become: true
  dnf:
    name:
      - zeal
      - git
      - firefox
      - dropbox
      - the_silver_searcher
      - keepassxc
      - chromium
      - gnucash
      - fzf
      - jq
      - ncdu
      - telegram-desktop
      - flameshot
      - thunderbird
      - lynis
      - NetworkManager-openvpn-gnome
      - podman
      - youtube-dl
      - vlc
      - yarnpkg
      - xclip
      - exfat-utils
      - fuse-exfat
      - darktable
      - libreoffice
      - hugo
      - nmap
      - arduino
      - speedtest-cli
      - bat
      - ImageMagick
      - gimp
      - gimp-heif-plugin
      - anki
      - ripgrep

- name: install docker
  include_tasks: docker.yml
  when: fedora.docker.install

- name: install snap packages
  include_tasks: snap.yml

- name: install AppImage packages
  include_tasks: appimage/main.yml
