- name: install packages for PopOS
  include_tasks: ubuntu.yml
  when: ansible_distribution == 'Pop!_OS'

- name: install packages for macOS
  include_tasks: macos.yml
  when: ansible_distribution == 'MacOSX'
