- name: install required packages
  include_tasks: packages/main.yml

- name: create directories for vim
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "~/.vim"
    - "~/.vim/autoload"
    - "~/.vim/undo"
    - "~/.vim/backup"
    - "~/.vim/swap"
    - "~/.vim/bundle"

- name: install vim-plug
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "~/.vim/autoload/plug.vim"
    mode: 0600

- name: link the configs
  file:
    src: "{{ dotfiles_dir }}/{{ item }}"
    path: "~/{{ item }}"
    state: link
  loop:
    - .vimrc
    - .vim/ultisnips
    - .vim/nerdtree_plugin

- name: install the plugins
  command: 'vim -E -s -c "source ~/.vimrc" -c PlugInstall -c qa'
  ignore_errors: true

- name: compile YCM
  command:
    chdir: "~/.vim/bundle/YouCompleteMe"
    cmd: "./install.py --clang-completer --go-completer --ts-completer --rust-completer"

