- name: install required packages
  include_tasks: packages/main.yml

- name: create directories for vim
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "~/.vim"
    - "~/.vim/undo"
    - "~/.vim/backup"
    - "~/.vim/swap"
    - "~/.vim/bundle"

- name: install Vundle
  git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: "~/.vim/bundle/Vundle.vim"
    update: no

- name: link the configs
  file:
    src: "{{ dotfiles_dir }}/{{ item }}"
    path: "~/{{ item }}"
    state: link
  loop:
    - .vimrc
    - .vim/ultisnips
    - .vim/nerdtree_plugin

- name: install the plugins
  command: 'vimx -E -s -c "source ~/.vimrc" -c PluginInstall -c qa'
  ignore_errors: true

- name: compile YCM
  command:
    chdir: "~/.vim/bundle/YouCompleteMe"
    cmd: "./install.py --clang-completer --go-completer --ts-completer --rust-completer"

