- name: setup syncthing for PopOS
  include_tasks: ubuntu/main.yml
  when: ansible_distribution == 'Pop!_OS'

- name: setup syncthing for macOS
  include_tasks: macos/main.yml
  when: ansible_distribution == 'MacOSX'
